// words.js
//
// `SOLUTIONS` = words the game may pick as the secret answer.
// `VALID_GUESSES` = words accepted as guesses (should be a superset of SOLUTIONS).
//
// Rules for entries here:
//   - Exactly 5 characters long as TYPED, where each of the following counts
//     as ONE character/tile: a-z, ü ö à è é ì ò û, and the hyphen "-".
//   - Case doesn't matter — everything is upper-cased at runtime for display
//     and lower-cased for comparison, consistently.

const SOLUTIONS = [
  "svelt"
];

// Valid guesses should be a superset of SOLUTIONS (every solution must also
// be guessable).
const VALID_GUESSES = [
  ...SOLUTIONS,
  "prüma",
  "leger",
  "pleds",
  "frasa",
  "uossa",
  "tuots",
  "posas",
  "vaira",
  "cloma",
  "plana",
  "massa",
  "svelt",
  "ellas",
  "cheus",
  "chapè",
  "disch",
  "saira",
  "cusir",
  "blers",
  "amias",
  "lavur",
  "peida",
  "avair",
  "güdar",
  "maisa",
  "uschè",
  "robas",
  "stinv",
  "choda",
  "plain",
  "brava",
  "quist",
  "posta",
  "quels",
  "brich",
  "ultim",
  "fraid",
  "bella",
  "pruna",
  "dalet",
  "viadi",
  "adieu",
  "agüds",
  "adura",
  "lodar",
  "terra",
  "naira",
  "porta",
  "daman",
  "badar",
  "riast",
  "riain",
  "riais",
  "terza",
  "rivar",
  "temas",
  "local",
  "giats",
  "grond",
  "autos",
  "trens",
  "ingio",
  "quant",
  "fraid",
  "savur",
  "stats",
  "sajat",
  "hajat",
  "vaiva",
  "faina",
  "faiva",
  "glüna",
  "mamma",
  "chasa",
  "salda",
  "festa",
  "stast",
  "stain",
  "stais",
  "stats",
  "mardi",
  "passa",
  "vaira",
  "gusta",
  "datta",
  "avant",
  "üetta",
  "daplü",
  "butia",
  "tutta",
  "bocca",
  "pensa",
  "forsa",
  "picla",
  "piclà",
  "venda",
  "vendü",
  "brich",
  "giais",
  "vegna",
  "quart",
  "mezdi",
  "gniva",
];

//p.244 ganz oben